[package]
name = "velleman_list_editor_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.32.1"
termion = "4.0.3"
glob = "0.3.0"